FROM jupyter/all-spark-notebook:latest
RUN pip install dbt-postgres
COPY ./dependencies/postgresql-42.6.0.jar /usr/local/spark/jars/postgresql-42.6.0.jar
RUN mkdir /home/jovyan/.dbt
COPY ./dependencies/profiles.yml /home/jovyan/.dbt/profiles.yml