processed:
  outputs:

    dev:
      type: postgres
      threads: 1
      host: citus
      port: 5432
      user: redshift
      pass: redshiftpass
      dbname: redshift
      schema: processed

    prod:
      type: postgres
      threads: [1 or more]
      host: [host]
      port: [port]
      user: [prod_username]
      pass: [prod_password]
      dbname: [dbname]
      schema: [prod_schema]

  target: dev

business:
  outputs:

    dev:
      type: postgres
      threads: 1
      host: citus
      port: 5432
      user: redshift
      pass: redshiftpass
      dbname: redshift
      schema: business

    prod:
      type: postgres
      threads: [1 or more]
      host: [host]
      port: [port]
      user: [prod_username]
      pass: [prod_password]
      dbname: [dbname]
      schema: [prod_schema]

  target: dev
